# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sum.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsum.proto\x12\x03sum\"\x1c\n\nSumRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32\x45\n\rSumCalculator\x12\x34\n\rcalculate_sum\x12\x0f.sum.SumRequest\x1a\x10.sum.SumResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMREQUEST']._serialized_start=18
  _globals['_SUMREQUEST']._serialized_end=46
  _globals['_SUMRESPONSE']._serialized_start=48
  _globals['_SUMRESPONSE']._serialized_end=77
  _globals['_SUMCALCULATOR']._serialized_start=79
  _globals['_SUMCALCULATOR']._serialized_end=148
# @@protoc_insertion_point(module_scope)
