model_list:
  - model_name: silverai/qwen2.5-vl-7b-instruct-awq
    litellm_params:
      model: hosted_vllm/Qwen2.5-VL-7B-Instruct-AWQ
      api_base: https://styleme--example-vllm-qwen2-5-vl-7b-serve.modal.run/v1
  - model_name: silverai/qwen3-vl-30b-a3b-instruct
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Instruct
      api_base: https://styleme--example-vllm-qwen3-vl-30b-a3b-serve.modal.run/v1